/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import javax.swing.JOptionPane;
import model.CabProfile;
import model.CabHistory;
/**
 *
 * @author hs_sa
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    
    CabHistory cabHistory;
    public CreateJPanel(CabHistory history) {
        initComponents();
        this.cabHistory = history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelRegDate = new javax.swing.JLabel();
        jLabelOccupied = new javax.swing.JLabel();
        jLabelBrand = new javax.swing.JLabel();
        jLabelManufacturingYear = new javax.swing.JLabel();
        jLabelCity = new javax.swing.JLabel();
        jLabelSeatNo = new javax.swing.JLabel();
        jLabelSerNo = new javax.swing.JLabel();
        jLabelModelNo = new javax.swing.JLabel();
        jLabelCertificate = new javax.swing.JLabel();
        jTextRegDate = new javax.swing.JTextField();
        jTextFieldBrand = new javax.swing.JTextField();
        jTextFieldManufacturingYr = new javax.swing.JTextField();
        jTextFieldCity = new javax.swing.JTextField();
        jTextFieldSeatNo = new javax.swing.JTextField();
        jTextFieldSerNo = new javax.swing.JTextField();
        jTextFieldModNo = new javax.swing.JTextField();
        jTextFieldCert = new javax.swing.JTextField();
        jCheckBoxOccupied = new javax.swing.JCheckBox();
        jSaveButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Car Details");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelRegDate.setText("Registration Date");

        jLabelOccupied.setText("Occupied");

        jLabelBrand.setText("Brand");

        jLabelManufacturingYear.setText("Manufacturing Year");

        jLabelCity.setText("City");

        jLabelSeatNo.setText("No. of Seats");

        jLabelSerNo.setText("Serial Number");

        jLabelModelNo.setText("Model Number");

        jLabelCertificate.setText("Certificate");

        jTextRegDate.setBackground(new java.awt.Color(153, 255, 255));

        jTextFieldBrand.setBackground(new java.awt.Color(153, 255, 255));

        jTextFieldManufacturingYr.setBackground(new java.awt.Color(153, 255, 255));

        jTextFieldCity.setBackground(new java.awt.Color(153, 255, 255));

        jTextFieldSeatNo.setBackground(new java.awt.Color(153, 255, 255));

        jTextFieldSerNo.setBackground(new java.awt.Color(153, 255, 255));

        jTextFieldModNo.setBackground(new java.awt.Color(153, 255, 255));

        jTextFieldCert.setBackground(new java.awt.Color(153, 255, 255));

        jCheckBoxOccupied.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxOccupiedActionPerformed(evt);
            }
        });

        jSaveButton.setBackground(new java.awt.Color(0, 153, 153));
        jSaveButton.setText("Save");
        jSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelCertificate)
                            .addComponent(jLabelModelNo)
                            .addComponent(jLabelOccupied)
                            .addComponent(jLabelRegDate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSeatNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelBrand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelManufacturingYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelSerNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(151, 151, 151)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCity, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldSeatNo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldSerNo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldModNo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldCert, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBoxOccupied)
                                .addGap(0, 47, Short.MAX_VALUE))
                            .addComponent(jTextRegDate)
                            .addComponent(jTextFieldBrand)
                            .addComponent(jTextFieldManufacturingYr)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jSaveButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelRegDate)
                            .addComponent(jTextRegDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelOccupied)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelBrand))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBoxOccupied)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelManufacturingYear)
                    .addComponent(jTextFieldManufacturingYr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCity)
                    .addComponent(jTextFieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSeatNo)
                    .addComponent(jTextFieldSeatNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSerNo)
                    .addComponent(jTextFieldSerNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelModelNo)
                    .addComponent(jTextFieldModNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCertificate)
                    .addComponent(jTextFieldCert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSaveButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveButtonActionPerformed
        // TODO add your handling code here:
        CabProfile profile = cabHistory.addNewCar();
        
        if (jTextRegDate.getText().isEmpty()|| jTextFieldBrand.getText().isEmpty() || jTextFieldManufacturingYr.getText().isEmpty() 
              || jTextFieldCity.getText().isEmpty() || jTextFieldSeatNo.getText().isEmpty() || jTextFieldSerNo.getText().isEmpty() 
              || jTextFieldModNo.getText().isEmpty() || jTextFieldCert.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "ENTER VALID DETAILS..! ");
        }
        else
        {
            String RegDate = jTextRegDate.getText();
            String brand = jTextFieldBrand.getText();
            int year = Integer.parseInt(jTextFieldManufacturingYr.getText());

            String city = jTextFieldCity.getText();
            int seats = Integer.parseInt(jTextFieldSeatNo.getText());
            String serial_number = jTextFieldSerNo.getText();
            String serialregex = "^[A-Z a-z]{1,5}[0-9]{1,5}$";
            if(!serial_number.matches(serialregex) || (serial_number.isEmpty()))
            {
                JOptionPane.showMessageDialog(this, "Enter Valid Serial Number!");
            }
            //else
            
                profile.setSerial_number(jTextFieldSerNo.getText());
                String model_number = jTextFieldModNo.getText();
            int certi_year = Integer.parseInt(jTextFieldCert.getText());
            
            
            if (this.jCheckBoxOccupied.isSelected())
            {
                profile.setOccupied("Yes");
            }
            
            profile.setBrand(brand);
            profile.setCerti_year(certi_year);
            profile.setCity(city);
            profile.setModel_number(model_number);
            profile.setSeats(seats);
            profile.setRegistration_date(RegDate);
            
            JOptionPane.showMessageDialog(this, "New Car Details added!");
            

      
            
            jTextRegDate.setText("");
            jTextFieldBrand.setText("");
            jTextFieldCity.setText("");
            jTextFieldSeatNo.setText("");
            jTextFieldSerNo.setText("");
            jTextFieldModNo.setText("");
            jTextFieldCert.setText("");
            jTextFieldManufacturingYr.setText("");
        }
    }//GEN-LAST:event_jSaveButtonActionPerformed

    private void jCheckBoxOccupiedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxOccupiedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxOccupiedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxOccupied;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBrand;
    private javax.swing.JLabel jLabelCertificate;
    private javax.swing.JLabel jLabelCity;
    private javax.swing.JLabel jLabelManufacturingYear;
    private javax.swing.JLabel jLabelModelNo;
    private javax.swing.JLabel jLabelOccupied;
    private javax.swing.JLabel jLabelRegDate;
    private javax.swing.JLabel jLabelSeatNo;
    private javax.swing.JLabel jLabelSerNo;
    private javax.swing.JButton jSaveButton;
    private javax.swing.JTextField jTextFieldBrand;
    private javax.swing.JTextField jTextFieldCert;
    private javax.swing.JTextField jTextFieldCity;
    private javax.swing.JTextField jTextFieldManufacturingYr;
    private javax.swing.JTextField jTextFieldModNo;
    private javax.swing.JTextField jTextFieldSeatNo;
    private javax.swing.JTextField jTextFieldSerNo;
    private javax.swing.JTextField jTextRegDate;
    // End of variables declaration//GEN-END:variables
}
