/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import model.CabProfile;
import model.CabHistory;
/**
 *
 * @author hs_sa
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    CabHistory cabHist;
    public MainJFrame() {
        initComponents();
        cabHist = new CabHistory();
        setData();
    }
    
    public void setData(){
     
        CabProfile CAR0 = cabHist.addNewCar();
        CAR0.setRegistration_date("2/10/2012");
        CAR0.setOccupied("yes");
        CAR0.setBrand("TESLA");
        CAR0.setYear(2010);
        CAR0.setCity("New York");
        CAR0.setSeats(4);
        CAR0.setSerial_number("TESLA98765");
        CAR0.setModel_number("TES12");
        CAR0.setCerti_year(2020);
        CAR0.setTime("14-07-2017 04:24:27");
        
        
        CabProfile CAR = cabHist.addNewCar();
        CAR.setRegistration_date("2/10/2016");
        CAR.setOccupied("yes");
        CAR.setBrand("TOYOTA");
        CAR.setYear(2012);
        CAR.setCity("Bengaluru");
        CAR.setSeats(8);
        CAR.setSerial_number("TOY432");
        CAR.setModel_number("TOY12");
        CAR.setCerti_year(2022);
        CAR.setTime("14-07-2017 04:24:27");
        
        CabProfile CAR1 = cabHist.addNewCar();
        CAR1.setRegistration_date("23/12/2014");
        CAR1.setOccupied("no");
        CAR1.setBrand("BMW");
        CAR1.setYear(2010);
        CAR1.setCity("Boston");
        CAR1.setSeats(5);
        CAR1.setSerial_number("BMW876");
        CAR1.setModel_number("BMW12");
        CAR1.setCerti_year(2020);
        CAR1.setTime("14-07-2017 04:24:27");
        
        
        CabProfile CAR3 = cabHist.addNewCar();
        CAR3.setRegistration_date("02/10/2021");
        CAR3.setOccupied("yes");
        CAR3.setBrand("BENZ");
        CAR3.setYear(2019);
        CAR3.setCity("Bengaluru");
        CAR3.setSeats(5);
        CAR3.setSerial_number("BEN432");
        CAR3.setModel_number("BEN12");
        CAR3.setCerti_year(2025);
        CAR3.setTime("14-07-2017 04:24:27");
          
        
        CabProfile CAR4 = cabHist.addNewCar();
        CAR4.setRegistration_date("02/10/2015");
        CAR4.setOccupied("yes");
        CAR4.setBrand("FERRARI");
        CAR4.setYear(2009);
        CAR4.setCity("Texas");
        CAR4.setSeats(5);
        CAR4.setSerial_number("BEN432");
        CAR4.setModel_number("FER12");
        CAR4.setCerti_year(2019);
        CAR4.setTime("14-07-2020 04:24:27");
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jCreateButton = new javax.swing.JButton();
        jSearchButton = new javax.swing.JButton();
        jViewButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 153, 153));

        jCreateButton.setBackground(new java.awt.Color(0, 153, 153));
        jCreateButton.setText("Create");
        jCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCreateButtonActionPerformed(evt);
            }
        });

        jSearchButton.setBackground(new java.awt.Color(0, 153, 153));
        jSearchButton.setText("Search");
        jSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchButtonActionPerformed(evt);
            }
        });

        jViewButton.setBackground(new java.awt.Color(0, 153, 153));
        jViewButton.setText("View");
        jViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jViewButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCreateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(jSearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jViewButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jCreateButton)
                .addGap(49, 49, 49)
                .addComponent(jSearchButton)
                .addGap(52, 52, 52)
                .addComponent(jViewButton)
                .addContainerGap(503, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCreateButtonActionPerformed
        // TODO add your handling code here:
        CreateJPanel Createpanel = new CreateJPanel(cabHist);
        jSplitPane1.setRightComponent(Createpanel);
        
    }//GEN-LAST:event_jCreateButtonActionPerformed

    private void jViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jViewButtonActionPerformed
        // TODO add your handling code here:
        ViewJPanel Viewpanel = new ViewJPanel(cabHist);
        jSplitPane1.setRightComponent(Viewpanel);
    }//GEN-LAST:event_jViewButtonActionPerformed

    private void jSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchButtonActionPerformed
        // TODO add your handling code here:
        
        SearchJPanel Searchpanel = new SearchJPanel(cabHist);
        jSplitPane1.setRightComponent(Searchpanel);
    }//GEN-LAST:event_jSearchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCreateButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jSearchButton;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton jViewButton;
    // End of variables declaration//GEN-END:variables
}
