/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author hs_sa
 */
import model.CabProfile;
import model.CabHistory;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    CabHistory history;
    
    public ViewJPanel(CabHistory history) {
        initComponents();
         this.history = history;
         
         paneUpdate.setVisible(false);
        paneView.setVisible(false);

        populateTable();
         
    }
    
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblCab.getModel();

        model.setRowCount(0);
//      System.out.println("size"+ history.getHistory().size());

        for (CabProfile CAB : history.getHistory()) {

            Object[] row = new Object[10];
            row[0] = CAB;
            row[1] = CAB.getOccupied();
            row[2] = CAB.getBrand();
            row[3] = CAB.getYear();
            row[4] = CAB.getCity();
            row[5] = CAB.getSeats();
            row[6] = CAB.getSerial_number();
            row[7] = CAB.getModel_number();
            row[8] = CAB.getCerti_year();

            model.addRow(row);

        }
    }

    private void Update(CabProfile ch) {

        Date currentTime = new Date();
        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
        String dateTime = dateFormat.format(currentTime);
        ch.setRegistration_date(jTextRegDate1.getText());
         if(this.jCheckBoxOccupiedUpdate.isSelected()){
           ch.setOccupied("yes"); 
        }else{
             ch.setOccupied("no"); 
         }
        ch.setBrand(jTextFieldBrand1.getText());
        ch.setYear(Integer.parseInt(jTextFieldManufacturingYr1.getText()));
        ch.setSerial_number(jTextFieldSerNo1.getText());
        ch.setSeats(Integer.parseInt(jTextFieldSeatNo1.getText()));
        ch.setModel_number(jTextFieldModNo1.getText());
        ch.setCity(jTextFieldCity1.getText());
        ch.setCerti_year(Integer.parseInt(jTextFieldCert1.getText()));
        ch.setTime(dateTime);
        populateTable();

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTable = new javax.swing.JScrollPane();
        tblCab = new javax.swing.JTable();
        jViewButton = new javax.swing.JButton();
        jUpdateButton = new javax.swing.JButton();
        jDeleteButton = new javax.swing.JButton();
        paneView = new javax.swing.JPanel();
        jLabelBrand = new javax.swing.JLabel();
        jTextFieldSeatNo = new javax.swing.JTextField();
        jLabelManufacturingYear = new javax.swing.JLabel();
        jTextFieldSerNo = new javax.swing.JTextField();
        jLabelCity = new javax.swing.JLabel();
        jTextFieldModNo = new javax.swing.JTextField();
        jLabelSeatNo = new javax.swing.JLabel();
        jTextFieldCert = new javax.swing.JTextField();
        jLabelSerNo = new javax.swing.JLabel();
        jCheckBoxOccupiedView = new javax.swing.JCheckBox();
        jLabelModelNo = new javax.swing.JLabel();
        jLabelCertificate = new javax.swing.JLabel();
        jTextRegDate = new javax.swing.JTextField();
        jTextFieldBrand = new javax.swing.JTextField();
        jLabelRegDate = new javax.swing.JLabel();
        jTextFieldManufacturingYr = new javax.swing.JTextField();
        jLabelOccupied = new javax.swing.JLabel();
        jTextFieldCity = new javax.swing.JTextField();
        paneUpdate = new javax.swing.JPanel();
        jLabelBrand1 = new javax.swing.JLabel();
        jTextFieldSeatNo1 = new javax.swing.JTextField();
        jLabelManufacturingYear1 = new javax.swing.JLabel();
        jTextFieldSerNo1 = new javax.swing.JTextField();
        jLabelCity1 = new javax.swing.JLabel();
        jTextFieldModNo1 = new javax.swing.JTextField();
        jLabelSeatNo1 = new javax.swing.JLabel();
        jTextFieldCert1 = new javax.swing.JTextField();
        jLabelSerNo1 = new javax.swing.JLabel();
        jCheckBoxOccupiedUpdate = new javax.swing.JCheckBox();
        jLabelModelNo1 = new javax.swing.JLabel();
        jLabelCertificate1 = new javax.swing.JLabel();
        jTextRegDate1 = new javax.swing.JTextField();
        jTextFieldBrand1 = new javax.swing.JTextField();
        jLabelRegDate1 = new javax.swing.JLabel();
        jTextFieldManufacturingYr1 = new javax.swing.JTextField();
        jLabelOccupied1 = new javax.swing.JLabel();
        jTextFieldCity1 = new javax.swing.JTextField();
        jButtonUpdateSubmit = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        tblCab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Registration Date", "Availability", "Brand", "Manufacturing", "City", "No. of Seats", "Serial Number", "Model Number", "Certificate"
            }
        ));
        jTable.setViewportView(tblCab);

        jViewButton.setText("View");
        jViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jViewButtonActionPerformed(evt);
            }
        });

        jUpdateButton.setText("Update");
        jUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateButtonActionPerformed(evt);
            }
        });

        jDeleteButton.setText("Delete");
        jDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteButtonActionPerformed(evt);
            }
        });

        paneView.setBackground(new java.awt.Color(255, 255, 255));

        jLabelBrand.setText("Brand");

        jTextFieldSeatNo.setBackground(new java.awt.Color(153, 255, 255));

        jLabelManufacturingYear.setText("Manufacturing Year");

        jTextFieldSerNo.setBackground(new java.awt.Color(153, 255, 255));

        jLabelCity.setText("City");

        jTextFieldModNo.setBackground(new java.awt.Color(153, 255, 255));

        jLabelSeatNo.setText("No. of Seats");

        jTextFieldCert.setBackground(new java.awt.Color(153, 255, 255));

        jLabelSerNo.setText("Serial Number");

        jCheckBoxOccupiedView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxOccupiedViewActionPerformed(evt);
            }
        });

        jLabelModelNo.setText("Model Number");

        jLabelCertificate.setText("Certificate");

        jTextRegDate.setBackground(new java.awt.Color(153, 255, 255));

        jTextFieldBrand.setBackground(new java.awt.Color(153, 255, 255));

        jLabelRegDate.setText("Registration Date");

        jTextFieldManufacturingYr.setBackground(new java.awt.Color(153, 255, 255));

        jLabelOccupied.setText("Occupied");

        jTextFieldCity.setBackground(new java.awt.Color(153, 255, 255));

        javax.swing.GroupLayout paneViewLayout = new javax.swing.GroupLayout(paneView);
        paneView.setLayout(paneViewLayout);
        paneViewLayout.setHorizontalGroup(
            paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
            .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paneViewLayout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelCertificate)
                        .addComponent(jLabelModelNo)
                        .addComponent(jLabelOccupied)
                        .addComponent(jLabelRegDate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelSeatNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelBrand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelManufacturingYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelSerNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(151, 151, 151)
                    .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldCity, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldSeatNo, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldSerNo, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldModNo, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldCert, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(paneViewLayout.createSequentialGroup()
                            .addComponent(jCheckBoxOccupiedView)
                            .addGap(0, 47, Short.MAX_VALUE))
                        .addComponent(jTextRegDate)
                        .addComponent(jTextFieldBrand)
                        .addComponent(jTextFieldManufacturingYr))
                    .addContainerGap(44, Short.MAX_VALUE)))
        );
        paneViewLayout.setVerticalGroup(
            paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
            .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paneViewLayout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(paneViewLayout.createSequentialGroup()
                            .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelRegDate)
                                .addComponent(jTextRegDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(jLabelOccupied)
                            .addGap(18, 18, 18)
                            .addComponent(jLabelBrand))
                        .addGroup(paneViewLayout.createSequentialGroup()
                            .addComponent(jCheckBoxOccupiedView)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelManufacturingYear)
                        .addComponent(jTextFieldManufacturingYr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelCity)
                        .addComponent(jTextFieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelSeatNo)
                        .addComponent(jTextFieldSeatNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelSerNo)
                        .addComponent(jTextFieldSerNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelModelNo)
                        .addComponent(jTextFieldModNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelCertificate)
                        .addComponent(jTextFieldCert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(33, Short.MAX_VALUE)))
        );

        paneUpdate.setBackground(new java.awt.Color(255, 255, 255));

        jLabelBrand1.setText("Brand");

        jTextFieldSeatNo1.setBackground(new java.awt.Color(153, 255, 255));

        jLabelManufacturingYear1.setText("Manufacturing Year");

        jTextFieldSerNo1.setBackground(new java.awt.Color(153, 255, 255));

        jLabelCity1.setText("City");

        jTextFieldModNo1.setBackground(new java.awt.Color(153, 255, 255));

        jLabelSeatNo1.setText("No. of Seats");

        jTextFieldCert1.setBackground(new java.awt.Color(153, 255, 255));

        jLabelSerNo1.setText("Serial Number");

        jCheckBoxOccupiedUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxOccupiedUpdateActionPerformed(evt);
            }
        });

        jLabelModelNo1.setText("Model Number");

        jLabelCertificate1.setText("Certificate");

        jTextRegDate1.setBackground(new java.awt.Color(153, 255, 255));

        jTextFieldBrand1.setBackground(new java.awt.Color(153, 255, 255));

        jLabelRegDate1.setText("Registration Date");

        jTextFieldManufacturingYr1.setBackground(new java.awt.Color(153, 255, 255));

        jLabelOccupied1.setText("Occupied");

        jTextFieldCity1.setBackground(new java.awt.Color(153, 255, 255));

        jButtonUpdateSubmit.setText("Submit");
        jButtonUpdateSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneUpdateLayout = new javax.swing.GroupLayout(paneUpdate);
        paneUpdate.setLayout(paneUpdateLayout);
        paneUpdateLayout.setHorizontalGroup(
            paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneUpdateLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jButtonUpdateSubmit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paneUpdateLayout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelCertificate1)
                        .addComponent(jLabelModelNo1)
                        .addComponent(jLabelOccupied1)
                        .addComponent(jLabelRegDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelSeatNo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelBrand1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelCity1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelManufacturingYear1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelSerNo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(151, 151, 151)
                    .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldCity1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldSeatNo1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldSerNo1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldModNo1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldCert1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(paneUpdateLayout.createSequentialGroup()
                            .addComponent(jCheckBoxOccupiedUpdate)
                            .addGap(0, 47, Short.MAX_VALUE))
                        .addComponent(jTextRegDate1)
                        .addComponent(jTextFieldBrand1)
                        .addComponent(jTextFieldManufacturingYr1))
                    .addContainerGap(44, Short.MAX_VALUE)))
        );
        paneUpdateLayout.setVerticalGroup(
            paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneUpdateLayout.createSequentialGroup()
                .addContainerGap(382, Short.MAX_VALUE)
                .addComponent(jButtonUpdateSubmit)
                .addContainerGap())
            .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paneUpdateLayout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(paneUpdateLayout.createSequentialGroup()
                            .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelRegDate1)
                                .addComponent(jTextRegDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(jLabelOccupied1)
                            .addGap(18, 18, 18)
                            .addComponent(jLabelBrand1))
                        .addGroup(paneUpdateLayout.createSequentialGroup()
                            .addComponent(jCheckBoxOccupiedUpdate)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldBrand1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelManufacturingYear1)
                        .addComponent(jTextFieldManufacturingYr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelCity1)
                        .addComponent(jTextFieldCity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelSeatNo1)
                        .addComponent(jTextFieldSeatNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelSerNo1)
                        .addComponent(jTextFieldSerNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelModelNo1)
                        .addComponent(jTextFieldModNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelCertificate1)
                        .addComponent(jTextFieldCert1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(57, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTable)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(paneView, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jViewButton)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jUpdateButton)
                        .addGap(234, 234, 234)
                        .addComponent(jDeleteButton)
                        .addGap(76, 76, 76))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paneUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTable, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jViewButton)
                    .addComponent(jUpdateButton)
                    .addComponent(jDeleteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paneUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(182, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jViewButtonActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblCab.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to View.");
            return;
        }
        
        paneUpdate.setVisible(false);
        paneView.setVisible(true);
        
        DefaultTableModel model = (DefaultTableModel) tblCab.getModel();
        CabProfile selectedCar = (CabProfile) model.getValueAt(selectedRowIndex, 0);
        if (String.valueOf(selectedCar.getOccupied()) == "yes") {
            jCheckBoxOccupiedView.setSelected(true);
            jCheckBoxOccupiedUpdate.setText("");
        } else {
            jCheckBoxOccupiedView.setSelected(false);
            jCheckBoxOccupiedUpdate.setText("");
        }
        
        jTextFieldBrand.setText(String.valueOf(selectedCar.getBrand()));
        jTextFieldSeatNo.setText(String.valueOf(selectedCar.getSeats()));
        jTextFieldCity.setText(String.valueOf(selectedCar.getCity()));
        jTextFieldManufacturingYr.setText((String.valueOf(selectedCar.getYear())));
        jTextFieldModNo.setText((String.valueOf(selectedCar.getModel_number())));
        jTextFieldSerNo.setText((String.valueOf(selectedCar.getSerial_number())));
        jTextRegDate.setText((String.valueOf(selectedCar.getRegistration_date())));
        jTextFieldCert.setText(String.valueOf(selectedCar.getCerti_year()));
    }//GEN-LAST:event_jViewButtonActionPerformed

    private void jCheckBoxOccupiedViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxOccupiedViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxOccupiedViewActionPerformed

    private void jCheckBoxOccupiedUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxOccupiedUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxOccupiedUpdateActionPerformed

    private void jDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteButtonActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblCab.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblCab.getModel();
        CabProfile selectedCar = (CabProfile) model.getValueAt(selectedRowIndex, 0);

        history.deleteCar(selectedCar);

        JOptionPane.showMessageDialog(this, "Car Details Deleted.");

        populateTable();
        
    }//GEN-LAST:event_jDeleteButtonActionPerformed

    private void jUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateButtonActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblCab.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to Update.");
            return;
        }

        paneView.setVisible(false);
        paneUpdate.setVisible(true);

        DefaultTableModel model = (DefaultTableModel) tblCab.getModel();
        CabProfile selectedCar = (CabProfile) model.getValueAt(selectedRowIndex, 0);
         if (String.valueOf(selectedCar.getOccupied()) == "yes") {
            jCheckBoxOccupiedUpdate.setSelected(true);
            jCheckBoxOccupiedUpdate.setText("");
        } else {
            jCheckBoxOccupiedUpdate.setSelected(false);
            jCheckBoxOccupiedUpdate.setText("");
        }
        jTextRegDate1.setText(String.valueOf(selectedCar.getRegistration_date()));
        jTextFieldBrand1.setText(String.valueOf(selectedCar.getBrand()));
        jTextFieldManufacturingYr1.setText(String.valueOf(selectedCar.getYear()));
        jTextFieldCity1.setText(String.valueOf(selectedCar.getCity()));
        jTextFieldSeatNo1.setText(String.valueOf(selectedCar.getSeats()));
        jTextFieldSerNo1.setText(String.valueOf(selectedCar.getSerial_number()));
        jTextFieldModNo1.setText(String.valueOf(selectedCar.getModel_number()));
        jTextFieldCert1.setText(String.valueOf(selectedCar.getCerti_year()));
    }//GEN-LAST:event_jUpdateButtonActionPerformed

    private void jButtonUpdateSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateSubmitActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblCab.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblCab.getModel();
        CabProfile selectedCar = (CabProfile) model.getValueAt(selectedRowIndex, 0);
        Update(selectedCar);
        paneUpdate.setVisible(false);
    }//GEN-LAST:event_jButtonUpdateSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonUpdateSubmit;
    private javax.swing.JCheckBox jCheckBoxOccupiedUpdate;
    private javax.swing.JCheckBox jCheckBoxOccupiedView;
    private javax.swing.JButton jDeleteButton;
    private javax.swing.JLabel jLabelBrand;
    private javax.swing.JLabel jLabelBrand1;
    private javax.swing.JLabel jLabelCertificate;
    private javax.swing.JLabel jLabelCertificate1;
    private javax.swing.JLabel jLabelCity;
    private javax.swing.JLabel jLabelCity1;
    private javax.swing.JLabel jLabelManufacturingYear;
    private javax.swing.JLabel jLabelManufacturingYear1;
    private javax.swing.JLabel jLabelModelNo;
    private javax.swing.JLabel jLabelModelNo1;
    private javax.swing.JLabel jLabelOccupied;
    private javax.swing.JLabel jLabelOccupied1;
    private javax.swing.JLabel jLabelRegDate;
    private javax.swing.JLabel jLabelRegDate1;
    private javax.swing.JLabel jLabelSeatNo;
    private javax.swing.JLabel jLabelSeatNo1;
    private javax.swing.JLabel jLabelSerNo;
    private javax.swing.JLabel jLabelSerNo1;
    private javax.swing.JScrollPane jTable;
    private javax.swing.JTextField jTextFieldBrand;
    private javax.swing.JTextField jTextFieldBrand1;
    private javax.swing.JTextField jTextFieldCert;
    private javax.swing.JTextField jTextFieldCert1;
    private javax.swing.JTextField jTextFieldCity;
    private javax.swing.JTextField jTextFieldCity1;
    private javax.swing.JTextField jTextFieldManufacturingYr;
    private javax.swing.JTextField jTextFieldManufacturingYr1;
    private javax.swing.JTextField jTextFieldModNo;
    private javax.swing.JTextField jTextFieldModNo1;
    private javax.swing.JTextField jTextFieldSeatNo;
    private javax.swing.JTextField jTextFieldSeatNo1;
    private javax.swing.JTextField jTextFieldSerNo;
    private javax.swing.JTextField jTextFieldSerNo1;
    private javax.swing.JTextField jTextRegDate;
    private javax.swing.JTextField jTextRegDate1;
    private javax.swing.JButton jUpdateButton;
    private javax.swing.JButton jViewButton;
    private javax.swing.JPanel paneUpdate;
    private javax.swing.JPanel paneView;
    private javax.swing.JTable tblCab;
    // End of variables declaration//GEN-END:variables
}
